FROM python:3.11-slim

WORKDIR /app

COPY requirements-generator.txt .
RUN pip install --no-cache-dir -r requirements-generator.txt

COPY src/ src/

CMD ["python", "-m", "src.generator.kafka_producer"]
